//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csdlnc_shopee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        public string MAHANGHOA { get; set; }
        public string TENHANGHOA { get; set; }
        public string MOTA { get; set; }
        public double GIATHANH { get; set; }
        public int SOLUONGTON { get; set; }
        public string LOAIHANGHOA { get; set; }
        public string HHFlag { get; set; }
        public Nullable<double> DANHGIA_HANGHOA { get; set; }
        public Nullable<System.DateTime> THOIHANSUDUNG { get; set; }
        public Nullable<int> SOLUONGDABAN { get; set; }
        public string HINHANH { get; set; }
    
        public virtual DANHMUC DANHMUC { get; set; }
    }
}
